app/index/__init__.py
from flask import Blueprint
from . import views

bp = Blueprint('index', __name__, template_folder='templates')

bp.add_url_rule('/', view_func=views.start_page, methods=['GET', 'POST'])

bp.add_url_rule('/lp', view_func=views.lp_page, methods=['GET', 'POST'])
bp.add_url_rule('/table', view_func=views.table_page, methods=['GET', 'POST'])
bp.add_url_rule('/analis', view_func=views.analis_page, methods=['GET', 'POST'])
bp.add_url_rule('/prlist', view_func=views.pr_list, methods=['GET', 'POST'])

app/index/views.py
from flask import render_template, request, redirect, url_for, jsonify
import json
from datetime import date
from app.models.proc_list import Proc_list
from app.models.lp_list import Lp_list
from app.models.lp_intervals import Lp_intervals
from wtfpeewee.orm import model_form
from wtforms.validators import (DataRequired, InputRequired)

inp_method = {1: 'табл.', 2: 'в/в', 3: 'в/м', 4: 'п/к'}

# Form = model_form(
#     Proc_list,
#     field_args={
#         'lp': dict(
#             label='lec',
#             render_kw={'class': 'form-input', 'type': 'text'},
#             validators=[DataRequired('значение не заполнено')]),
#         'data1': dict(
#             label='дата нач приема',
#             render_kw={'class': 'form-input', 'type': 'date'},
#             validators=[DataRequired('значение не заполнено')]),
#         'data2': dict(
#             label='дата ок приема',
#             render_kw={'class': 'form-input', 'type': 'date'}),
#         'schema': dict(
#             # label='схема',
#             render_kw={'id': 'schema', 'class': 'form-input',
#                        'type': 'text', 'style': 'display: none'},
#             validators=[DataRequired('не указано вреемя приема')]),
#         'dayscount': dict(
#             label='kol-vo',
#             render_kw={'class': 'form-input', 'type': 'number'},
#             validators=[DataRequired('значение не заполнено')]),
#     })


def start_page():
    # form = Form(request.form or None)
    # if form.data2.data == '':
    #    form.data2.data = date(1,1,1)
    # print(form.data2.data)
    id_pat = 123
    his = 123
    lists = get_pl_by_pat(id_pat, his)
    if request.method == 'POST':
        return redirect(url_for('index.lp_page'))
    return render_template('index.html', title='Процедурный лист', lists=lists)


def lp_page():
    pl=''
    id = request.args.get('id')
    if (request.method == 'GET') and id:
        # получение данных по проц листу
        pl = get_pl_by_id(id)
        #pl = json.dumps({'pl': pl})
        # print(pl)
    # form = Form(request.form or None)
    # if form.data2.data == '':
    #    form.data2.data = date(1,1,1)
    # print(form.data2.data)
    if request.method == 'POST':
        # pass
        # print(request.form)
        proc_list = json.loads(request.form['proc_list'])
        print(proc_list)
        
        id = save_el(proc_list)
       # print(a['lp'])
        # or k in a['lp']:
        #    print(a['lp'][k])
        return jsonify({'url': url_for('index.lp_page', id=id)})
    return render_template('proc_list.html', title='Процедурный лист',
                           inp_method=inp_method, today=date.today(),
                           pl=pl)


def table_page():
    if request.method == 'POST':
        pass
    return render_template('table.html', title='Процедурный лист')


def analis_page():
    if request.method == 'POST':
        pass
    return render_template('analis.html', title='Процедурный лист')


def pr_list():
    # form = Form(request.form or None)
    # if form.data2.data == '':
    #    form.data2.data = date(1,1,1)
    # print(form.data2.data)
    if request.method == 'POST':
        pass
        # save_el()
        #print(json.loads(request.data))
        #a = json.loads(request.form['schema'])
        # for k in a:
        #    print(a[k]['time1'])
        # redirect(url_for('index.start_page'))
    return render_template('pr_list.html', title='Процедурный лист')


def save_el(proc_list):
    if proc_list['id'] != 'null':
        (Proc_list
         .update(pat=proc_list['pat'],
                 his=proc_list['his'],
                 date_start=proc_list['date_start'],
                 doc=proc_list['doc'],
                 dep=proc_list['dep'])
         .where(Proc_list.id == proc_list['id'])
         .execute())
        el = proc_list['id']
    else:    
        el = Proc_list(pat=proc_list['pat'],
                       his=proc_list['his'],
                       date_start=proc_list['date_start'],
                       doc=proc_list['doc'],
                       dep=proc_list['dep'])
        el.save()

    if proc_list['id'] == 'null': #временное ограничение на запись уже сущ проц листа
        for elem in proc_list['lp']:
            lp = proc_list['lp'][elem]
            # new_el_lp = Lp_list(proc_list=new_el,
            #                     lp_name=lp['name'],
            #                     lp_id=lp['id'],
            #                     date_start=lp['date_start'],
            #                     days=lp['days_count'])
            new_el_lp = Lp_list(proc_list=el,
                                lp_name=lp['name'],
                                date_start=lp['date_start'],
                                days=lp['days_count'])
            new_el_lp.save()

            for t in lp['times']:
                new_el_t = Lp_intervals(lp=new_el_lp,
                                time_start=t['time1'],
                                time_end=t['time2'],
                                doza=t['doza'],
                                method=t['method'])
                new_el_t.save()

    return el


def get_pl_by_id(id):
    query = (Proc_list
            .select()
            .where(Proc_list.id == id)
            .namedtuples())
    for elem in query:
        pl = {
                'id': elem.id,
                'pat': elem.pat,
                'his': elem.his,
                'doc': elem.doc,
                'dep': elem.dep,
                'date_start': elem.date_start.strftime('%Y-%m-%d'),
                'lp': get_lp_by_pl_id(id)
                }  
    return pl 


def get_lp_by_pl_id(id):
    query = (Lp_list
            .select()
            .where(Lp_list.proc_list == id)
            .order_by(Lp_list.id)
            .namedtuples())
    
    lp = {}
    i = 0
    for elem in query:
        lp[i] = {
                 'id': elem.id,
                 'name': elem.lp_name,
                 'date_start': elem.date_start.strftime('%Y-%m-%d'),
                 'days_count': elem.days,
                 'times': get_times(elem.id)
                 }
        i = i+1

    return lp


def get_times(id):
    query_t = (Lp_intervals
            .select()
            .where(Lp_intervals.lp == id)
            .order_by(Lp_intervals.id)
            .namedtuples())

    times = []
    # i = 0
    for elem in query_t:
        # i = i+1
        times.append({
                    'id': elem.id,
                    'time1': elem.time_start,
                    'time2': elem.time_end,
                    'doza': elem.doza,
                    'method': elem.method
                    })

    return times


def get_pl_by_pat(id_pat, his):
    query = (Proc_list
            .select()
            .where((Proc_list.pat == id_pat) &
                   (Proc_list.his == his))
            .namedtuples())
    pl = []
    for elem in query:
        pl.append({
            'id': elem.id,
            'doc': elem.doc,
            'dep': elem.dep,
            'date_start': elem.date_start.strftime('%Y-%m-%d')
            })
    # print(pl)
    return pl

app/index/templates/analis.html
{% set navname = 'navanalis' %}
{% extends 'base.html' %}
{% block content %}
в разработке
{% endblock %}

app/index/templates/index.html
{% set navname = 'navlp' %}
{% extends 'base.html' %}
{% block content %}
<div class='container'>
	<form id='form' action='' method='post' class='form-inline' novalidate>
		<div class="row">
			<button type='submit' id='add' class='btn btn-default'>Добавить</button>
		</div>
		<ol>
			{#<li><a href={{ url_for('index.pr_list') }} target='_blank'>Процедурный лист test</a></li>#}
			{% for elem in lists %}
				<li><a href={{ url_for('index.lp_page', id = elem['id']) }}>Процедурный лист от {{ elem['date_start'] }} отд. {{ elem['dep'] }} (спец. id {{ elem['doc'] }})</a></li>
			{% endfor %}
		</ol>
	</form>
</div>	
{% endblock %}

app/index/templates/pr_list.html
{% set navname = 'navlp' %}
{% extends 'base.html' %}
{% block content %}
<div class='container'>
	<form id='form' action='' method='post' class='form-inline' novalidate>
		<table>
			<tr>
				{% for j in range(30) %}
					<td>j</td>
				{% endfor %}
			</tr>
		</table>
	</form>
</div>	
{% endblock %}

app/index/templates/proc_list.html
<script>
 	let str_pl = '{{ pl|tojson }}';
	var pl = JSON.parse(str_pl);
</script>
{% set navname = 'navlp' %}
{% extends 'base.html' %}
{% block content %}
<div class='container'>
	<div class='container'>
	<div class='form-group col-sm-3'>
		<label for='pl_date_start'>дата начала проц. листа</label>
		<input name='pl_date_start' id='pl_date_start' type='date' class='form-control'>
	</div>	
	<div class='form-group col-sm-3'>
		<label for='dep'>отделение</label>
		<input name='dep' id='dep' type='text' class='form-control'>
	</div>	
	<div class='form-group col-sm-3'>
		<label for='doc'>врач</label>
		<input name='doc' id='doc' type='text' class='form-control'>
	</div>	
	</div>
	<div>
	<ul class="nav nav-tabs">
		{% if navname == 'navlp' %}
	  		<li role="presentation" class="active"><a href={{ url_for('index.lp_page') }}>Лекарственные препараты</a></li>
	  	{% else %}
			<li role="presentation"><a href={{ url_for('index.lp_page') }}>Лекарственные препараты</a></li>
		{% endif %}	
		{% if navname == 'navtable' %}
	  		<li role="presentation" class="active"><a href={{ url_for('index.table_page') }}>Стол</a></li>
	  	{% else %}
			<li role="presentation"><a href={{ url_for('index.table_page') }}>Стол</a></li>
		{% endif %}	
		{% if navname == 'navanalis' %}
	  		<li role="presentation" class="active"><a href={{ url_for('index.analis_page') }}>Анализы</a></li>
	  	{% else %}
			<li role="presentation"><a href={{ url_for('index.analis_page') }}>Анализы</a></li>
		{% endif %}	
	</ul>
	</div>
	<br>

	<form id='form' action='' method='post' class='form-inline' novalidate>
		<div class="row">
			<div class='col-sm-9'>
				<div class='row'>
					<div class='form-group sm-text col-sm-3'>
						<label for='lp'>ЛП</label>
						<input name='lp' id='lp' type='text' class='form-control'>
					</div>
					<div class='form-group col-sm-2 sm-text'>
						<label for='doz'>доза</label>
						<input name='doz' id='doz' type='text' class='form-control small'>	
					</div>
					<div class='form-group col-sm-2 sm-text'>
						<label for='date-start'>принимать с</label>
						<input name='date-start' id='date-start' type='date' class='form-control date' required='' value={{ today }}>	
					</div>
					<div class='form-group col-sm-2 sm-text'>
						<label for='days-count'>кол-во дней</label>
						<input name='days-count' id='days-count' type='number' class='form-control small' value=1>	
					</div>
					<div class='form-group col-sm-2 sm-text'>
						<label for='inp-meth'>способ ввода</label>
						<select name='inp-meth' id='inp-meth' class='form-control'>
							{% for n in inp_method %}
								{% if n == 1 %}
									<option value='{{ n }}' selected=''>{{ inp_method[n] }}</option>
								{% else %}
									<option value='{{ n }}'>{{ inp_method[n] }}</option>
								{% endif %}	
							{% endfor %}
						</select>	
					</div>
					<div id='time-box' class='form-group sm-text col-sm-12'>
						<label for='time-box'>время приема</label>
						<div id='time-box-inp' class='input-group input-group-sm'>
							<input id='txt' type='text' class='form-control' owner='general' disabled value=0>
							<div class='input-group-btn'>		
								{% for i in range(24) %}
									<button type='button' id='b{{ i+1 }}' class='btn btn-default txt_btn' owner='general' onclick='clickbtn("txt")'>{{ i+1 }}</button>
								{% endfor %}
							</div>
						</div>
					</div>
					<div class='checkbox col-sm-3'>
						<label><input id='comb_time' type="checkbox" checked="true" onclick='checkbox()'> Объединить время</label>	
					</div>
				</div>
			</div>
			<button id='add_lp' type='button' class='btn btn-default'><i class='glyphicon glyphicon-plus'></i></button>
		</div>
		<br>
		<div id='prep' class='row col-sm-10'>				
			<div id='lp-list' class='list-group col-sm-4'>
				{#<div class='row'><div class='col-sm-10'><button class='list-group-item'>1</button></div></div>
				<div class='row'>
					<div class='col-sm-10'>
						<button class='list-group-item active'>2</button>
					</div>
					<button class='btn btn-link'><i class="glyphicon glyphicon-remove"></i></button>
				</div>	
				<div class='row'><button class='list-group-item '>3</button></div>#}
			</div>
			<div id='lp-info' class='col-sm-7'></div>
		</div>
		<div  class='row col-sm-10'>
			<button id='save_lp' type='submit' class='btn btn-success'>Сохранить</button>
			<a href='/' class='btn btn-default'>Назад </a>
		</div>
	</form>
</div>

{% endblock %}

app/index/templates/table.html
{% set navname = 'navtable' %}
{% extends 'base.html' %}
{% block content %}
в разработке
{% endblock %}